AWSTemplateFormatVersion: 2010-09-09
Description: Peter Ocansey | A Cloud Guru Challenge (Improve application performance using Amazon ElastiCache) - This template deploys RDS Postgres using Infrastracture As Code


Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resources
    Type: String
  
  DBInstanceID:
    Default: mydbinstance
    Description: My database instance
    Type: String

  DBName:
    Default: mydb
    Description: My database
    Type: String
  
  DBInstanceClass:
    Default: db.t2.micro
    Description: DB instance class
    Type: String
  
  DBAllocatedStorage:
    Default: '50'
    Description: The size of the database (GiB)
    Type: Number
  
  DBUsername:
    NoEcho: 'true'
    Description: Username for PostgreSQL database access
    Type: String

  DBPassword:
    NoEcho: 'true'
    Description: Password PostgreSQL database access
    Type: String



Resources:
  
  DBWebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80 and SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
  
  DBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      DBSecurityGroupIngress:
        EC2SecurityGroupName:
          Ref: DBWebServerSecurityGroup
      GroupDescription: Frontend Access

  DBElasticCacheInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      DBSecurityGroups:
      - Ref: DBSecurityGroup
      Engine: postgres
      EngineVersion: 12.7
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      MonitoringInterval: '60'
      MonitoringRoleArn: 'arn:aws:iam::123456789012:role/rds-monitoring-role'