AWSTemplateFormatVersion: 2010-09-09
Description: Peter Ocansey | A Cloud Guru Challenge (Improve application performance using Amazon ElastiCache) - This template deploys Redis Elastic Cache using Infrastracture As Code


Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resources
    Type: String

  ElasticCacheName:
    Default: elastic-cache-cluster
    Description: The elastic cache cluster name
    Type: String
  
  ElasticCachePort:
    Default: '6379'
    Description: The elastic cache port
    Type: Number


Resources:
  
  ElasticacheSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Elasticache Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '6379'
          ToPort: '6379'
          CidrIp: 0.0.0.0/0
          

  ElasticacheCluster:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:    
      Engine: redis
      ClusterName: !Ref ElasticCacheName
      CacheNodeType: cache.r6g.large
      NumCacheNodes: '1'
      Port: !Ref ElasticCachePort
      VpcSecurityGroupIds:
        - !GetAtt 
          - ElasticacheSecurityGroup
          - GroupId
        - Fn::ImportValue: !Sub "${EnvironmentName}-AppServerSecurityGroupID"

Outputs: 

    RedisCacheEndpoint:
        Description: The public url to elastic cache cluster
        Value: !GetAtt ElasticacheCluster.RedisEndpoint.Address
        Export:
          Name: !Sub ${EnvironmentName}-RedisCacheEndpoint-URL

    RedisCacheEndpointPort:
        Description: The port to elastic cache cluster
        Value: !GetAtt ElasticacheCluster.RedisEndpoint.Port
        Export:
          Name: !Sub ${EnvironmentName}-RedisCacheEndpointPort