AWSTemplateFormatVersion: 2010-09-09
Description: Peter Ocansey | A Cloud Guru Challenge (Improve application performance using Amazon ElastiCache) - This template deploys Redis Elastic Cache using Infrastracture As Code


Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resources
    Type: String
  
  DBInstanceID:
    Default: mydbinstance
    Description: My database instance
    Type: String

  DBName:
    Default: mydb
    Description: My database
    Type: String
  
  DBInstanceClass:
    Default: db.t2.micro
    Description: DB instance class
    Type: String
  
  DBAllocatedStorage:
    Default: '50'
    Description: The size of the database (GiB)
    Type: Number
  
  DBUsername:
    NoEcho: 'true'
    Description: Username for PostgreSQL database access
    Type: String

  DBPassword:
    NoEcho: 'true'
    Description: Password PostgreSQL database access
    Type: String



Resources:
  
  ElasticacheSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Elasticache Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '11211'
          ToPort: '11211'
          SourceSecurityGroupName: !Ref InstanceSecurityGroup

  ElasticacheCluster:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:    
      Engine: memcached
      CacheNodeType: cache.t2.micro
      NumCacheNodes: '1'
      VpcSecurityGroupIds:
        - !GetAtt 
          - ElasticacheSecurityGroup
          - GroupId